name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Stats
      run: go run github.com/arran4/github-level/cmd/stats

    - name: Text Levels
      run: go run github.com/arran4/github-level/cmd/leveltext

